#!/bin/bash

script_name="${1:-main}"
script_path="$(dirname "$0")/../${script_name}.py"

if [[ ! -f "$script_path" ]]; then
    echo "Error: '$script_path' does not exist."
    exit 1
fi

/home/TokYy/Venv/PyTorch/bin/python "$script_path" "${@:2}"